### ISSUE TITLE
No SD Card shortcut

### ISSUE THREAD

**Issue by ghost** [llelectronics/filecat#8]
Hi, I installed your app in my XA2 (SFOS 3.2) but the shortcut to access directly to the SD Card is greyed out:

![Screenshot_20191107_001](https://user-images.githubusercontent.com/14874690/68410212-ab56e480-0188-11ea-91a1-152162398340.png)

May the problem be that my sd card is encrypted? That means it needs to be unlocked and mounted manually after every boot, which creates problem with the tracker, afaik.

Tell me what you need to debug this problem

**Comment by llelectronics** [comment]
We had that already. Sadly I did not hear back from the other user reporting that issue: https://github.com/llelectronics/videoPlayer/issues/36

I need a way to identify the sd card. Can you check the mount point and device name with the **mount** command in terminal.

**Comment by ghost** [comment]
Here is the output of `mount`:

![Screenshot_20191107_233649](https://user-images.githubusercontent.com/14874690/68433699-7b730580-01b7-11ea-9fc8-4cdd55858028.png)

I guess this is the line which interest you (the last):

`/dev/mapper/luks-e47db01e-f162-4b28-b819-5691e6b558a2 on /run/media/nemo/Smartphone type ext4 (rw,nosuid,nodev,relatime,data=ordered,uhelper=udisks2)`

I am not very familiar with mount, so if you need some other information using specific flags please let me know.

**Comment by ghost** [comment]
Hi! I am answering here instead of openrepos, I guess it's easier to keep track of things here.
I tried the RPM you linked in the comments, [this one](https://llelectronics.dd-dns.de/s/4smBPc97qmrYFqz), and it works!
I guess that this RPM is a previous version to the commit you linked me to in the next comment, so if you need more testing, I am available to do so. By the way, since you are already working on this, it would be very nice if the app would be able to detect an USB OTG device and, only if one is found, show an entry in the places menu.
I would not use it, since I don't have a USB-C OTG device, but it's just an idea that came to my mind and I thought it would be right to share.

**Comment by llelectronics** [comment]
Thanks see this commit. 
https://github.com/llelectronics/filecat/commit/0b1cf4d0f7af209bdeeb07c34ee3c27a36fb2a81
USB-OTG support already landed. I will close this ticket as soon as the new version is out.
Thanks for the feedback

**Comment by llelectronics** [comment]
Fixed with this commit https://github.com/llelectronics/filecat/commit/1a955bfae32ef64b96beb40d74b7be89699fd14a

**Comment by ghost** [comment]
Thank you very much!
